"""
Django settings for cead project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ

# from .axes import *
from .db import *
from .email import *
from .cors import *
from .lang import *
from .drf import *
from .jwt import *
from .session import *
from .spectacular import *
from .ssl import *

env = environ.Env()
environ.Env.read_env()

from pathlib import Path

# Configure python-decouple's Environment Variables loader
from cead.env import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-sad9nbu^y)_=vv78s4^k%e7zmo!9&w!$z=0s04*wqe1)krggmr",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = ["sistemascead.ufjf.br", "sistemascead.marangon.cead.lan", "127.0.0.1"]

# In your environment variables set
# ALLOWED_HOSTS="host-one.com,.host-two.com"
# To use this setting
ENV_ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=None)
if ENV_ALLOWED_HOSTS is not None:
    ALLOWED_HOSTS += [x.strip() for x in ENV_ALLOWED_HOSTS.split(",")]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",
    "dal",
    "dal_select2",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    "cead.autenticacao",
    "cead.editais",
    "cead.ficha",
    "cead.financeiro",
    "cead.inscricao",
    "cead.lanca_frequencia",
    "cead.moodle",
    "cead.transmissao",
    "cead.wordpress",
    "cead",
]

MIDDLEWARE = [
    # "axes.middleware.AxesMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "cead.urls"

CSRF_COOKIE_SAMESITE = "None"  # Permitir cookies em contexto cross-site
CSRF_COOKIE_SECURE = True  # Apenas envia cookies sobre HTTPS

CSRF_TRUSTED_ORIGINS = [
    "https://sistemascead.ufjf.br",
    "https://sistemascead.marangon.cead.lan",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "ficha", "templates"),
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cead.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/backend/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "cead", "ficha", "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "cead", "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

RAIZ_ARQUIVOS_UPLOAD = "/usr/local/www/cead-static/documentos/"

LOGIN_URL = "/backend/entrar/"
LOGIN_REDIRECT_URL = "/"

# Para servir com redirect no nginx adicionando /backend
# Precisa disso para gerar os links para download na validacao de arquivos
FORCE_SCRIPT_NAME = "/backend"

# Ha telas adicionais de login intermediarias, para proteger o conteudo
LOGIN_REDIRECT_URLS = {
    "/backend/entrar/": "/",
    "/editais/aprovar/": "/editais/aprovar/",
    "/editais/associar_edital_pessoa/": "/editais/associar_edital_pessoa/",
    "/editais/relatorio/": "/editais/relatorio/",
    "/editais/validar/": "/editais/validar/",
    "/financeiro/associar_edital_funcaoficha_oferta/": "/financeiro/associar_edital_funcaoficha_oferta/",
    "/financeiro/bolsistas/": "/financeiro/bolsistas/",
    "/lanca_frequencia/administrativo/disciplinas/": "/lanca_frequencia/administrativo/disciplinas/",
    "/lanca_frequencia/administrativo/relatorio/": "/lanca_frequencia/administrativo/relatorio/",
    "/lanca_frequencia/": "/lanca_frequencia/",
    "/moodle/relatorio/": "/moodle/relatorio/",
}
